repos:
  # Pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  # Python formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  # Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Type checking - disabled for now due to extensive type annotation work needed
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         [
  #           types-requests,
  #           types-PyYAML,
  #           types-click,
  #           types-cryptography,
  #           types-toml,
  #         ]
  #       args: [--ignore-missing-imports]

  # Security - disabled for now due to extensive security scan work needed
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.5
  #   hooks:
  #     - id: bandit
  #       additional_dependencies: [pbr]
  #       args: [-f, json, -o, bandit-report.json, --skip, B101, --quiet]
  #       exclude: tests/

  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args:
          [
            --ignore,
            DL3008,
            --ignore,
            DL3009,
            --ignore,
            DL3059,
            --ignore,
            DL3021,
            --ignore,
            SC2102,
          ]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^(\.github/|monitoring/)

  # Local hooks
  - repo: local
    hooks:
      # OpenAPI regeneration
      - id: generate-openapi
        name: Generate OpenAPI documentation
        entry: poetry run python scripts/generate_openapi.py
        language: system
        files: ^(src/character_ai/web/|src/character_ai/api/|scripts/generate_openapi.py)
        pass_filenames: false
        always_run: false
