name: CI Disabled - Manual Development Only

on:
  workflow_dispatch:

jobs:
  # Placeholder job - CI disabled due to GitHub Actions disk space issues
  disabled:
    name: CI Disabled
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: CI Disabled Notice
        run: |
          echo "=========================================="
          echo "CI IS DISABLED DUE TO DISK SPACE ISSUES"
          echo "=========================================="
          echo ""
          echo "GitHub Actions runners are running out of disk space"
          echo "even before our code runs. This is a GitHub infrastructure"
          echo "issue, not a code issue."
          echo ""
          echo "For development, run locally:"
          echo "  make lint      - Code quality checks"
          echo "  make test      - Run tests"
          echo "  make security  - Security checks"
          echo ""
          echo "Pre-commit hooks are still active for code quality."
          echo "=========================================="
