name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write
  pull-requests: read

jobs:
  # Ultra-minimal linting
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Ultra-minimal setup
        run: |
          # Aggressive cleanup first
          sudo rm -rf /usr/share/doc /usr/share/man /usr/share/info
          sudo apt-get clean
          pip cache purge || true

          # Install only what we need
          poetry install --only main
          poetry run pip install black isort ruff --no-cache-dir

      - name: Run linting
        run: |
          poetry run black --check src/ tests/
          poetry run isort --check-only src/ tests/
          poetry run ruff check src/ tests/

  # Ultra-minimal security
  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Ultra-minimal security setup
        run: |
          # Aggressive cleanup first
          sudo rm -rf /usr/share/doc /usr/share/man /usr/share/info
          sudo apt-get clean
          pip cache purge || true

          # Install only security tools
          poetry install --only main
          poetry run pip install bandit safety --no-cache-dir
          # Fix numpy vulnerability
          poetry run pip install numpy==1.22.2 --force-reinstall --no-cache-dir

      - name: Run security checks
        run: |
          poetry run bandit -r src/ --severity-level medium
          poetry run safety check --short-report

  # Ultra-minimal tests
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Ultra-minimal test setup
        run: |
          # Aggressive cleanup first
          sudo rm -rf /usr/share/doc /usr/share/man /usr/share/info
          sudo apt-get clean
          pip cache purge || true

          # Install only test essentials
          poetry install --only main
          poetry run pip install pytest pytest-asyncio PyJWT cryptography types-PyYAML types-requests types-psutil --no-cache-dir
          poetry run pip install numpy==1.22.2 --force-reinstall --no-cache-dir

      - name: Run tests
        run: |
          CAI_ENABLE_API_STARTUP=0 poetry run pytest -v -p pytest_asyncio tests/ --maxfail=5
