name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.7.1'

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run security checks
        run: |
          poetry run safety check --short-report
          poetry run bandit -r src/ --severity-level medium

      - name: Run tests
        run: poetry run pytest tests/ --maxfail=3

      - name: Auto-merge PR
        if: success()
        uses: fastify/github-action-merge-dependency-updates@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: squash
